# Generated by Django 3.2.8 on 2021-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreate', '0002_catalog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
